export const contacts = [
  {
    'id': 1,
    'username': 'Essie',
    'avatar': require('@/assets/images/portrait/small/avatar-s-3.jpg'),
    'lastname': 'Vaill',
    'company': 'Litronic Industries',
    'address': '14225 Hancock Dr',
    'city': 'Anchorage',
    'country': 'Anchorage',
    'state': 'AK',
    'zip': '99515',
    'phone': '907-345-0962',
    'fax': '907-345-1215',
    'email': 'essie@vaill.com',
    'web': 'http://www.essievaill.com',
    'followers': 3574,
    'created_at': '20.10.2020',
    'commission': 0,
    'image_signs': 1,
    'proofed': 1,
    'lot_status_admin': 1,
    'lot_status_user': 1
  },
  {
    'id': 2,
    'username': 'Cruz',
    'avatar': require('@/assets/images/portrait/small/avatar-s-11.jpg'),
    'lastname': 'Roudabush',
    'company': 'Meridian Products',
    'address': '2202 S Central Ave',
    'city': 'Phoenix',
    'country': 'Maricopa',
    'state': 'AZ',
    'zip': '85004',
    'phone': '602-252-4827',
    'fax': '602-252-4009',
    'email': 'cruz@roudabush.com',
    'web': 'http://www.cruzroudabush.com',
    'followers': 6548,
    'created_at': '20.10.2020',
    'commission': 0,
    'image_signs': 1,
    'proofed': 1,
    'lot_status_admin': 0,
    'lot_status_user': 1
  },
  {
    'id': 3,
    'username': 'Billie',
    'avatar': require('@/assets/images/portrait/small/avatar-s-10.jpg'),
    'lastname': 'Tinnes',
    'company': 'D & M Plywood Inc',
    'address': '28 W 27th St',
    'city': 'New York',
    'country': 'New York',
    'state': 'NY',
    'zip': '10001',
    'phone': '212-889-5775',
    'fax': '212-889-5764',
    'email': 'billie@tinnes.com',
    'web': 'http://www.billietinnes.com',
    'followers': 3536,
    'created_at': '20.10.2020',
    'commission': 0,
    'image_signs': 1,
    'proofed': 0,
    'lot_status_admin': 1,
    'lot_status_user': 1
  },
  {
    'id': 4,
    'username': 'Zackary',
    'avatar': require('@/assets/images/portrait/small/avatar-s-13.jpg'),
    'lastname': 'Mockus',
    'company': 'Metropolitan Elevator Co',
    'address': '286 State St',
    'city': 'Perth Amboy',
    'country': 'Middlesex',
    'state': 'NJ',
    'zip': '08861',
    'phone': '732-442-0638',
    'fax': '732-442-5218',
    'email': 'zackary@mockus.com',
    'web': 'http://www.zackarymockus.com',
    'followers': 1497,
    'created_at': '20.10.2020',
    'commission': 1,
    'image_signs': 0,
    'proofed': 0,
    'lot_status_admin': 1,
    'lot_status_user': 1
  },
  {
    'id': 5,
    'username': 'Rosemarie',
    'avatar': require('@/assets/images/portrait/small/avatar-s-8.jpg'),
    'lastname': 'Fifield',
    'company': 'Technology Services',
    'address': '3131 N Nimitz Hwy  #-105',
    'city': 'Honolulu',
    'country': 'Honolulu',
    'state': 'HI',
    'zip': '96819',
    'phone': '808-836-8966',
    'fax': '808-836-6008',
    'email': 'rosemarie@fifield.com',
    'web': 'http://www.rosemariefifield.com',
    'followers': 4812,
    'created_at': '20.10.2020',
    'commission': 1,
    'image_signs': 0,
    'proofed': 0,
    'lot_status_admin': 1,
    'lot_status_user': 1
  },
  {
    'id': 6,
    'username': 'Bernard',
    'avatar': require('@/assets/images/portrait/small/avatar-s-3.jpg'),
    'lastname': 'Laboy',
    'company': 'Century 21 Keewaydin Prop',
    'address': '22661 S Frontage Rd',
    'city': 'Channahon',
    'country': 'Will',
    'state': 'IL',
    'zip': '60410',
    'phone': '815-467-0487',
    'fax': '815-467-1244',
    'email': 'bernard@laboy.com',
    'web': 'http://www.bernardlaboy.com',
    'followers': 6891,
    'created_at': '20.10.2020',
    'commission': 0,
    'image_signs': 1,
    'proofed': 0,
    'lot_status_admin': 1,
    'lot_status_user': 1
  },
  {
    'id': 7,
    'username': 'Sue',
    'avatar': require('@/assets/images/portrait/small/avatar-s-7.jpg'),
    'lastname': 'Haakinson',
    'company': 'Kim Peacock Beringhause',
    'address': '9617 N Metro Pky W',
    'city': 'Phoenix',
    'country': 'Maricopa',
    'state': 'AZ',
    'zip': '85051',
    'phone': '602-953-2753',
    'fax': '602-953-0355',
    'email': 'sue@haakinson.com',
    'web': 'http://www.suehaakinson.com',
    'followers': 5787,
    'created_at': '20.10.2020',
    'commission': 0,
    'image_signs': 1,
    'proofed': 0,
    'lot_status_admin': 1,
    'lot_status_user': 1
  },
  {
    'id': 8,
    'username': 'Valerie',
    'avatar': require('@/assets/images/portrait/small/avatar-s-3.jpg'),
    'lastname': 'Pou',
    'company': 'Sea Port Record One Stop Inc',
    'address': '7475 Hamilton Blvd',
    'city': 'Trexlertown',
    'country': 'Lehigh',
    'state': 'PA',
    'zip': '18087',
    'phone': '610-395-8743',
    'fax': '610-395-6995',
    'email': 'valerie@pou.com',
    'web': 'http://www.valeriepou.com',
    'followers': 8990,
    'created_at': '20.10.2020',
    'commission': 1,
    'image_signs': 1,
    'proofed': 1,
    'lot_status_admin': 1,
    'lot_status_user': 0
  },
  {
    'id': 9,
    'username': 'Lashawn',
    'avatar': require('@/assets/images/portrait/small/avatar-s-1.jpg'),
    'lastname': 'Hasty',
    'company': 'Kpff Consulting Engineers',
    'address': '815 S Glendora Ave',
    'city': 'West Covina',
    'country': 'Los Angeles',
    'state': 'CA',
    'zip': '91790',
    'phone': '626-960-6738',
    'fax': '626-960-1503',
    'email': 'lashawn@hasty.com',
    'web': 'http://www.lashawnhasty.com',
    'followers': 2131,
    'created_at': '20.10.2020',
    'commission': 1,
    'image_signs': 1,
    'proofed': 1,
    'lot_status_admin': 0,
    'lot_status_user': 0
  },
  {
    'id': 10,
    'username': 'Marianne',
    'avatar': require('@/assets/images/portrait/small/avatar-s-3.jpg'),
    'lastname': 'Earman',
    'company': 'Albers Technologies Corp',
    'address': '6220 S Orange Blossom Trl',
    'city': 'Orlando',
    'country': 'Orange',
    'state': 'FL',
    'zip': '32809',
    'phone': '407-857-0431',
    'fax': '407-857-2506',
    'email': 'marianne@earman.com',
    'web': 'http://www.marianneearman.com',
    'followers': 1992,
    'created_at': '20.10.2020',
    'commission': 1,
    'image_signs': 1,
    'proofed': 1,
    'lot_status_admin': 0,
    'lot_status_user': 0
  },
  {
    'id': 11,
    'username': 'Justina',
    'avatar': require('@/assets/images/portrait/small/avatar-s-3.jpg'),
    'lastname': 'Dragaj',
    'company': 'Uchner, David D Esq',
    'address': '2552 Poplar Ave',
    'city': 'Memphis',
    'country': 'Shelby',
    'state': 'TN',
    'zip': '38112',
    'phone': '901-327-5336',
    'fax': '901-327-2911',
    'email': 'justina@dragaj.com',
    'web': 'http://www.justinadragaj.com',
    'followers': 7149,
    'created_at': '20.10.2020',
    'commission': 1,
    'image_signs': 1,
    'proofed': 1,
    'lot_status_admin': 1,
    'lot_status_user': 0
  },
  {
    'id': 12,
    'username': 'Mandy',
    'avatar': require('@/assets/images/portrait/small/avatar-s-5.jpg'),
    'lastname': 'Mcdonnell',
    'company': 'Southern Vermont Surveys',
    'address': '343 Bush St Se',
    'city': 'Salem',
    'country': 'Marion',
    'state': 'OR',
    'zip': '97302',
    'phone': '503-371-8219',
    'fax': '503-371-1118',
    'email': 'mandy@mcdonnell.com',
    'web': 'http://www.mandymcdonnell.com',
    'followers': 1329,
    'created_at': '20.10.2020',
    'commission': 1,
    'image_signs': 1,
    'proofed': 0,
    'lot_status_admin': 0,
    'lot_status_user': 1
  },
  {
    'id': 13,
    'username': 'Conrad',
    'avatar': require('@/assets/images/portrait/small/avatar-s-3.jpg'),
    'lastname': 'Lanfear',
    'company': 'Kahler, Karen T Esq',
    'address': '49 Roche Way',
    'city': 'Youngstown',
    'country': 'Mahoning',
    'state': 'OH',
    'zip': '44512',
    'phone': '330-758-0314',
    'fax': '330-758-3536',
    'email': 'conrad@lanfear.com',
    'web': 'http://www.conradlanfear.com',
    'followers': 2906,
    'created_at': '20.10.2020',
    'commission': 1,
    'image_signs': 1,
    'proofed': 1,
    'lot_status_admin': 0,
    'lot_status_user': 1
  },
  {
    'id': 14,
    'username': 'Cyril',
    'avatar': require('@/assets/images/portrait/small/avatar-s-4.jpg'),
    'lastname': 'Behen',
    'company': 'National Paper & Envelope Corp',
    'address': '1650 S Harbor Blvd',
    'city': 'Anaheim',
    'country': 'Orange',
    'state': 'CA',
    'zip': '92802',
    'phone': '714-772-5050',
    'fax': '714-772-3859',
    'email': 'cyril@behen.com',
    'web': 'http://www.cyrilbehen.com',
    'followers': 7784,
    'created_at': '20.10.2020',
    'commission': 1,
    'image_signs': 1,
    'proofed': 1,
    'lot_status_admin': 1,
    'lot_status_user': 0
  },
  {
    'id': 15,
    'username': 'Shelley',
    'avatar': require('@/assets/images/portrait/small/avatar-s-3.jpg'),
    'lastname': 'Groden',
    'company': 'Norton, Robert L Esq',
    'address': '110 Broadway St',
    'city': 'San Antonio',
    'country': 'Bexar',
    'state': 'TX',
    'zip': '78205',
    'phone': '210-229-3017',
    'fax': '210-229-9757',
    'email': 'shelley@groden.com',
    'web': 'http://www.shelleygroden.com',
    'followers': 2012,
    'created_at': '20.10.2020',
    'commission': 1,
    'image_signs': 1,
    'proofed': 0,
    'lot_status_admin': 1,
    'lot_status_user': 0
  }
]
